### ISSUE TITLE
List or Remove registered users

### ISSUE THREAD

**Issue by sniketh** [oyooyo/keyble#13]
First, thanks for the keyble.  It's exactly what I was looking for once I realized that the eqiva door locker had not base station for remote control.

I'm using under Raspbian, and it's working just fine.  I was just wondering:

-Is there a way to remove registered users?
-Is there a way to list registered users?
-Is there a way to log actions made by users?

**Comment by oyooyo** [comment]
Hello,

sorry for the (very) late reply, I hadn't even noticed this issue until 5 minutes ago.

I'm afraid none of those features is supported by keyble. My original motivation behind keyble was just to be able to control the smart door lock from my PC/via MQTT. Since a number of people asked for it, I once considered implementing some more features (including the ones you asked for), but ultimately I never did; and since Eqiva has meanwhile discontinued the product, I will most probably not implement any more features in the future as well.

So using the vendor's smartphone app is currently the only way to do the things you asked for.
