### ISSUE TITLE
Disadvantages of Equiva Lock

### ISSUE THREAD

**Issue by unaiur** [oyooyo/keyble#42]
Hi @oyooyo ! I have read that you no longer are using this lock. Can I ask why?

I am planning to replace a HMIP smart lock because I cannot open the door when there is no electricity at home (which sadly is not so infrequent).

Thank you for your efforts!

**Comment by oyooyo** [comment]
The main reason I stopped using the lock was that the computer I was controlling it from is simply too far away from the lock, so establishing a Bluetooth connection between computer and smart lock turned out to be a big problem in my home.
There would be ways to get around that problem, for example by installing an additional Raspberry Pi near the smart lock, but I didn't want to do that.

Apart from that, the smart lock is perfectly fine, the hardware is good etc. Especially for situations like you describe, where there is no electricity, and you would thus be controlling the smart lock from your smartphone with the official smartphone app, standing right in front of the door, this smart lock should be pretty much ideal.

**Comment by oyooyo** [comment]
I only just realized that since you already have HMIP smart lock, you probably want to control the smart lock from both your smartphone (for example when there is no electricity) but also from a smart home system.

I do not know the HMIP smart lock, but I assume that the eqiva smart lock has indeed at least two disadvantages when compared to the HMIP:
- Controlling the eqiva lock via a computer running keyble is most probably less reliable and stable than via HMIP. One major source of problems when using keyble is the communication via Bluetooth LE. keyble uses a popular node.js library called "noble" for Bluetooth LE communication, but unfortunately the original developer of this library has stopped development several years ago.
- I assume that the HMIP smart lock reacts pretty much instantly when you order it to do some action. That's different with the eqiva smart lock - it can take several seconds until the smart lock will react, because establishing the connection to the smart lock takes some time. That can be avoided by setting keyble up to always staying connected to the smart lock, but in that case, you could for example no longer control the smart lock via the smartphone app as well, because there can always only be one connection to the smart lock.
